<a href="https://colab.research.google.com/github/julianramirez19m/julianramirez19m.github.io/blob/main/creando_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
my_list = [1,2,3,4,5]
print(np.array(my_list))

[1 2 3 4 5]


In [ ]:
print(np.random.rand(2,2))

[[0.05843797 0.92003014]
 [0.78016707 0.85252878]]


In [ ]:
 import numpy as np

In [ ]:
list(range(0,10)) #dato inicial 0 y dato stop es 10

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
np.arange(0,10)  #Este método de NumPy nos permite generar arrays sin definir previamente una lista.

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,20,2) #el dato inicial es 0, el dato de stop es 20 y el step es 2 que va a dar la lista de 2 en 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
np.zeros((5,5)) # Nos permite definir estructuras o esquemas mediante 0

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones((5,5)) # Nos permite definir estructuras o esquemas mediante 1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.linspace(0,10,5) #Permite generar una array definiendo un inicio, un final y cuantas divisiones tendrá.

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
np.eye(5) #También podemos crear una matriz con una diagonal de 1 y el resto de 0.

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.random.rand() #Otro método importante es generar números aleatorios.

0.12748729313938778

In [ ]:
np.random.rand(4) #También se pueden generar vectores.

array([0.02755904, 0.97669795, 0.144522  , 0.96917334])

In [ ]:
np.random.rand(4,5) #Tambien se pueden generar matrices

array([[0.14946898, 0.94716118, 0.94419444, 0.52473753, 0.76456832],
       [0.99249217, 0.14494074, 0.43951948, 0.49174488, 0.98215523],
       [0.85775742, 0.88215255, 0.50617518, 0.78474297, 0.05000221],
       [0.02726182, 0.66547966, 0.5809529 , 0.28121312, 0.66033028]])

In [ ]:
np.random.randint(0,30) #NumPy nos permite también generar números enteros En este caso números enteros entre el 1 y 30

6

In [ ]:
np.random.randint(0,30,(3,3)) #También podemos llevarlos a una estructura definida.

array([[ 4, 26, 19],
       [21, 12,  6],
       [24,  6, 26]])

# funcion shape y reshape

In [ ]:
import numpy as np

In [ ]:
arr = np.random.randint(0,10,(2,3))
arr

array([[7, 2, 2],
       [6, 2, 4]])

In [ ]:
arr.shape #Indica la forma del arreglo.

(2, 3)

In [ ]:
arr

array([[7, 2, 2],
       [6, 2, 4]])

In [ ]:
arr.reshape(1,6)  #transforma el arreglo mientras se mantengan los elementos.

array([[7, 2, 2, 6, 2, 4]])

In [ ]:
np.reshape(arr,(1,6))

array([[7, 2, 2, 6, 2, 4]])

In [ ]:
np.reshape(arr,(2,3), "C") #Se puede hacer un reshape como lo haría C.

array([[7, 2, 2],
       [6, 2, 4]])

In [ ]:
np.reshape(arr,(2,3), 'F') #Se puede hacer un reshape como lo haria en Fortran "F"

array([[7, 2, 2],
       [6, 2, 4]])

In [ ]:
np.reshape(arr,(2,3), "A") #Además, existe la opción de hacer reshape según como esté optimizado nuestro computador. En este caso es como en C.

array([[7, 2, 2],
       [6, 2, 4]])

In [ ]:
#Reto
#1.Crear un array de cualquier dimensión y cambiar sus dimensiones.
#2.Intenta cambiar el array de forma que no respete la estructura original

In [ ]:
import numpy as np

In [ ]:
arr = np.random.randint(0,10,(3,4))
arr

array([[9, 3, 8, 9],
       [7, 9, 5, 8],
       [7, 7, 9, 7]])

In [ ]:
np.reshape(arr,(2,6))

array([[9, 3, 8, 9, 7, 9],
       [5, 8, 7, 7, 9, 7]])

In [ ]:
np.reshape(arr,(1,12))

array([[9, 3, 8, 9, 7, 9, 5, 8, 7, 7, 9, 7]])

# Funciones principales de Numpy

In [ ]:
import numpy as np

In [ ]:
arr = np.random.randint(0,10,10)
arr

array([1, 3, 8, 4, 2, 5, 5, 0, 4, 0])

In [ ]:
matriz = arr.reshape(2,5)
matriz

array([[1, 3, 8, 4, 2],
       [5, 5, 0, 4, 0]])

In [ ]:
arr.max() #Para el máximo numero del vector

8

In [ ]:
matriz.max(0) #Para el máximo numero de la matriz por columna(0), por fila(1)

array([5, 5, 8, 4, 2])

In [ ]:
arr.argmax() # nos devuelve la posición del elemento o el indice de donde esta el mayor elemento

2

In [ ]:
matriz.argmax(0) # En el caso de la matriz nos muestra con un 1 dónde se encuentra el mayor entre las columnas

array([1, 1, 0, 0, 0])

In [ ]:
arr.min() #Para el menor numero del vector

0

In [ ]:
matriz.min(0) #Para el minimo numero de la matriz por columna(0), por fila(1)

array([1, 3, 0, 4, 0])

In [ ]:
arr.argmin() # nos devuelve la posición del elemento o el indice de donde esta el menor elemento

7

In [ ]:
matriz.argmin(0) # En el caso de la matriz nos muestra con un 1 dónde se encuentra el menor entre las columnas

array([0, 0, 1, 0, 1])

In [ ]:
arr

array([1, 3, 8, 4, 2, 5, 5, 0, 4, 0])

In [ ]:
arr.ptp() #Podemos saber la distancia entre el valor más bajo con el más alto.

8

In [ ]:
matriz


array([[1, 3, 8, 4, 2],
       [5, 5, 0, 4, 0]])

In [ ]:
matriz.ptp(0) #Podemos saber la distancia entre el valor más bajo con el más alto.entre columnas ya que es una matriz

array([4, 2, 8, 0, 2])

In [ ]:
arr

array([1, 3, 8, 4, 2, 5, 5, 0, 4, 0])

In [ ]:
arr.sort() #Ordenar los elementos
arr

array([0, 0, 1, 2, 3, 4, 4, 5, 5, 8])

In [ ]:
np.percentile(arr, 50) #Obtener un percentil

3.5

In [ ]:
arr

array([0, 0, 1, 2, 3, 4, 4, 5, 5, 8])

In [ ]:
np.median(arr) #mediana

3.5

In [ ]:
np.median(matriz,0) #Mediana de una matriz

array([2. , 2. , 3. , 3.5, 5.5])

In [ ]:
np.std(arr) #Desviacion estandar

2.4

In [ ]:
np.std(matriz,0) #Desviacion estandar de una matriz 

array([2. , 2. , 2. , 1.5, 2.5])

In [ ]:
np.var(arr) #Varianza

5.76

In [ ]:
np.var(matriz,0) #Varianza de una matriz

array([4.  , 4.  , 4.  , 2.25, 6.25])

In [ ]:
np.mean(arr) #Promedio

3.2

In [ ]:
np.mean(matriz,0) #Promedio entre columnas de una matriz

array([2. , 2. , 3. , 3.5, 5.5])

In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([5,6])

In [ ]:
np.concatenate((a,b), axis = 0)

ValueError: ignored

In [ ]:
np.ndim(a)

2

In [ ]:
np.ndim(b)

1

In [ ]:
b = np.expand_dims(b, axis = 0) #Debemos poner ‘b’ en 2 dimensiones también
np.concatenate((a,b), axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
np.concatenate((a,b.T), axis = 1) #Como ‘b’ es una fila y no una columna, no se puede concatenar a menos que se aplique la transpuesta.La transpuesta pone nuestro array en sentido opuesto, si el array original es (1,2), con la transpuesta quedará (2,1)

array([[1, 2, 5],
       [3, 4, 6]])

# Comando copy .copy()

In [ ]:
#.copy() nos permite copiar un array de NumPy en otra variable de tal forma que al modificar
#el nuevo array los cambios no se vean reflejados en array original.

In [ ]:
import numpy as np

In [ ]:
arr1 = np.arange(0,10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
trozo_de_arr = arr1[0:6]
trozo_de_arr

array([0, 1, 2, 3, 4, 5])

In [ ]:
trozo_de_arr[:] = 0 #Queremos pasar todas nuestras variables a 0
trozo_de_arr

array([0, 0, 0, 0, 0, 0])

In [ ]:
arr1 #Se han modificado los datos del array original porque seguía haciendo referencia a esa variable.

array([0, 0, 0, 0, 0, 0, 6, 7, 8, 9])

In [ ]:
arr_copy = arr1.copy() #Esta función te ayudará a prevenir muchos errores y tener más confianza a la hora de manipular los datos
arr_copy[:] = 100
arr_copy
arr1

array([0, 0, 0, 0, 0, 0, 6, 7, 8, 9])